# Generated by Django 3.0.7 on 2020-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0004_auto_20200621_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlappshortener',
            name='shortener',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
